"""Generate weekly opportunity reports."""

from datetime import datetime
from typing import List
from .models import OpportunityCluster
from .scoring import rank_clusters


def generate_report(clusters: List[OpportunityCluster], output_format: str = "markdown") -> str:
    """
    Generate a weekly opportunity report from clusters.
    
    Args:
        clusters: List of opportunity clusters
        output_format: "markdown" or "json"
    
    Returns:
        Formatted report string
    """
    if output_format == "json":
        return _generate_json_report(clusters)
    else:
        return _generate_markdown_report(clusters)


def _generate_markdown_report(clusters: List[OpportunityCluster]) -> str:
    """Generate markdown report."""
    now = datetime.now()
    
    # Rank clusters by score
    ranked_clusters = rank_clusters(clusters)
    high_score_clusters = [c for c in ranked_clusters if c.priority_score >= 650]
    
    # Build report
    lines = [
        "# Market Problem Scanner — Weekly Report",
        "",
        f"**Generated:** {now.strftime('%Y-%m-%d %H:%M')}",
        "",
        "## Summary",
        "",
        f"- **Clusters analyzed:** {len(clusters)}",
        f"- **Promising opportunities (priority ≥650):** {len(high_score_clusters)}",
        f"- **Total pain points:** {sum(c.total_mentions for c in clusters)}",
        "",
        "---",
        "",
        "## Top Opportunities",
        "",
    ]
    
    # Show top 5 opportunities
    top_clusters = ranked_clusters[:5]
    
    for i, cluster in enumerate(top_clusters, 1):
        lines.extend([
            f"### {i}. {cluster.title}",
            "",
            f"**Pain Score:** {cluster.avg_score:.1f}/40 | **Priority:** {cluster.priority_score} | **Profitability:** {cluster.profitability_score}/35 | **Build Probability:** {cluster.build_probability_score}/35 | **Band:** {cluster.priority_band}",
            "",
            f"**Mentions:** {cluster.total_mentions} | **Domain:** {cluster.domain}",
            "",
            f"**Audience:** {cluster.audience}",
            "",
            f"**Summary:** {cluster.executive_summary or 'Pending strategic review'}",
            "",
        ])
        
        if cluster.monetization_strategy:
            lines.extend([
                f"**Monetization:** {cluster.monetization_strategy}",
                "",
            ])
        
        if cluster.mvp_approach:
            lines.extend([
                f"**MVP Approach:** {cluster.mvp_approach}",
                "",
            ])

        if cluster.monetization_guess or cluster.mvp_shape or cluster.next_validation_step:
            lines.extend([
                f"**Monetization Guess:** {cluster.monetization_guess or 'needs validation'}",
                "",
                f"**MVP Shape:** {cluster.mvp_shape or 'needs validation'}",
                "",
                f"**Missing Data:** {cluster.missing_data or 'none obvious'}",
                "",
                f"**Risk Notes:** {cluster.risk_notes or 'none obvious'}",
                "",
                f"**Next Validation Step:** {cluster.next_validation_step or 'collect more evidence'}",
                "",
            ])
        
        # Show evidence (first 3 pain points)
        if cluster.pain_points:
            lines.extend([
                "**Evidence:**",
                "",
            ])
            
            for j, pain in enumerate(cluster.pain_points[:3], 1):
                lines.extend([
                    f"{j}. *\"{pain.quote[:150]}...\"*",
                    f"   - Source: {pain.source_url or 'fixture'}",
                    f"   - Score: {pain.total_score}/40",
                    "",
                ])
        
        lines.append("---")
        lines.append("")
    
    # Next steps
    lines.extend([
        "## Next Steps",
        "",
        "1. Review top 3 opportunities with human judgment",
        "2. Validate monetization hypotheses",
        "3. Create AI Daily Idea drafts for approved opportunities",
        "4. Open PR with new ideas",
        "",
        "---",
        "",
        f"*Report generated by Market Problem Scanner v0.4.0*",
    ])
    
    return "\n".join(lines)


def _generate_json_report(clusters: List[OpportunityCluster]) -> str:
    """Generate JSON report."""
    import json
    
    ranked_clusters = rank_clusters(clusters)
    
    report = {
        "generated_at": datetime.now().isoformat(),
        "summary": {
            "total_clusters": len(clusters),
            "high_score_count": len([c for c in clusters if c.priority_score >= 650]),
            "total_pain_points": sum(c.total_mentions for c in clusters),
        },
        "top_opportunities": [c.to_dict() for c in ranked_clusters[:5]],
    }
    
    return json.dumps(report, indent=2)
